### PR TITLE
Get request id from transport instance

### PR DESCRIPTION
**Pull request by faern**
Before this PR the id of each request is determined by the RPC client instance itself. Since many clients can possibly share the same transport instance, this can lead to duplicate ids over the same connection, something that can potentially make requests and responses mix up. This is not a real problem in the existing transport impl with Hyper since Hyper will manage matching responses to requests. But it's a theoretical problem for transports that does not do this.

With this PR we should more forcefully adhere to the JSON-RPC standard with unique IDs for each request over the same connection.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/14)

### CODE REVIEW

**Comment by simonasker** [comment]
*[core/src/lib.rs, line 125 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14#-KsNziaNgfORxjqVvtPE:-KsNziaNgfORxjqVvtPF:b7bjl64) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/3172c98de065ddf3d83c7347edb6f7561a22be41/core/src/lib.rs#L125)):*
> ```Rust
> pub trait Transport<E: ::std::error::Error + Send + 'static>
>     : Clone + Send + 'static {
>     /// Returns an id that has yet not been used on this sender instance. used by the RPC clients
> ```

`s/yet not/not yet/` and `s/. used/. Used/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14)*

**Comment by simonasker** [comment]
*[http/src/lib.rs, line 60 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14#-KsO-OAAutCO7kaZboMd:-KsO-OAAutCO7kaZboMe:bb70w76) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/3172c98de065ddf3d83c7347edb6f7561a22be41/http/src/lib.rs#L60)):*
> ```Rust
> }
> 
> type CoreSender = mpsc::UnboundedSender<(Request, oneshot::Sender<Result<Vec<u8>>>)>;
> ```

Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14)*

**Comment by simonasker** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14)*

**Comment by faern** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[core/src/lib.rs, line 125 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14#-KsNziaNgfORxjqVvtPE:-KsO18Qrmer04JFysoDP:b-896fix) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/3172c98de065ddf3d83c7347edb6f7561a22be41/core/src/lib.rs#L125)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

`s/yet not/not yet/` and `s/. used/. Used/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14)*

**Comment by simonasker** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/14#-:-KsO1UNhTKNhCfSk0KPa:bnfp4nl)*

**Pull request merged**
