### PR TITLE
Update CHANGELOG with 0.2.0 changes and later

### PR DESCRIPTION
**Pull request by faern**
Forgot to update the changelog before releasing. Better late than never.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/jsonrpc-client-rs/20)

### CODE REVIEW

**Comment by simonasker** [comment]
*[CHANGELOG.md, line 9 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20#-KtEOrd658GAyap4146H:-KtEOrd658GAyap4146I:bvs1ygu) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/2dd1bd6eb1ba5204181ce970d00aa7745fd8f83a/CHANGELOG.md#L9)):*
> ```Markdown
> ## [Unreleased]
> ### Changed
> - Made internal macro `expand_params` hidden from documentation.
> ```

I'm not sure if this is worth being to strict about but I thought I'd bring it up anyway. Should we stick to one conjugate form for verbs? In commits we to stick to imperative (e.g "make") but here you use past tense in some places (e.g "made", "rewrote"). I can't find any specific mention of this on keepachangelog.com but they do seem to stick to imperative for the changes themselves even though the category headings are written in past tense ("changed", "added", "fixed", and so on).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 9 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20#-KtEOrd658GAyap4146H:-KtFfe5FvO1f3g6-A1pH:brsti5c) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/2dd1bd6eb1ba5204181ce970d00aa7745fd8f83a/CHANGELOG.md#L9)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

I'm not sure if this is worth being to strict about but I thought I'd bring it up anyway. Should we stick to one conjugate form for verbs? In commits we to stick to imperative (e.g "make") but here you use past tense in some places (e.g "made", "rewrote"). I can't find any specific mention of this on keepachangelog.com but they do seem to stick to imperative for the changes themselves even though the category headings are written in past tense ("changed", "added", "fixed", and so on).
</blockquote></details>

Sounds good! Nice if we can stick to one form I agree! I changed to imperative form.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20)*

**Comment by simonasker** [comment]
*[CHANGELOG.md, line 9 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20#-KtEOrd658GAyap4146H:-KtG2rjHvqmj6K9WYHzU:b38k2vc) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/2dd1bd6eb1ba5204181ce970d00aa7745fd8f83a/CHANGELOG.md#L9)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Sounds good! Nice if we can stick to one form I agree! I changed to imperative form.
</blockquote></details>

You changed in the wrong direction :open_mouth: It should be "make", "change", and "rewrite".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 9 at r1](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20#-KtEOrd658GAyap4146H:-KtG4fvSDjgD1EK6Pke0:b2scrkr) ([raw file](https://github.com/mullvad/jsonrpc-client-rs/blob/2dd1bd6eb1ba5204181ce970d00aa7745fd8f83a/CHANGELOG.md#L9)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

You changed in the wrong direction :open_mouth: It should be "make", "change", and "rewrite".
</blockquote></details>

... Fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20)*

**Comment by simonasker** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/jsonrpc-client-rs/20#-:-KtG5FwH8qvhHjuhydx4:bnfp4nl)*

**Pull request merged**
